[workspace]
resolver = "3"
members = [ "netlink-bindings", "netlink-socket", "reverse-lookup", "codegen" ]

[patch.crates-io]
# TODO: Remove when argh is updated past 0.1.13 
argh = { git = "https://github.com/one-d-wide/argh.git", branch = "improve_usage" }
